#!/usr/bin/env python3
"""
Collect Referenced Images Script

Reads processed JSONL files, extracts all image_path entries, and creates a subset
folder containing only the referenced images while preserving the directory structure.
"""

import argparse
import json
import os
import shutil
import sys
from pathlib import Path
from typing import List, Set
import zipfile


def extract_image_paths(jsonl_files: List[str]) -> Set[str]:
    """Extract all unique image paths from JSONL files."""
    image_paths = set()
    
    for jsonl_file in jsonl_files:
        print(f"📖 Reading {jsonl_file}...")
        with open(jsonl_file, 'r') as f:
            for line_num, line in enumerate(f, 1):
                try:
                    data = json.loads(line.strip())
                    if 'image_path' in data:
                        image_paths.add(data['image_path'])
                except json.JSONDecodeError as e:
                    print(f"⚠️  Warning: Invalid JSON on line {line_num} in {jsonl_file}: {e}")
                    continue
    
    print(f"📊 Found {len(image_paths)} unique image paths")
    return image_paths


def collect_images(
    image_paths: Set[str], 
    src_root: str, 
    dst_root: str, 
    mode: str = "copy"
) -> List[str]:
    """Collect images from src_root to dst_root."""
    collected = []
    missing = []
    
    src_path = Path(src_root)
    dst_path = Path(dst_root)
    
    # Create destination directory
    dst_path.mkdir(parents=True, exist_ok=True)
    
    print(f"🔄 Collecting images using {mode} mode...")
    
    for image_path in sorted(image_paths):
        # Handle both absolute and relative paths
        if os.path.isabs(image_path):
            src_file = Path(image_path)
        else:
            src_file = src_path / image_path
        
        # Create destination path preserving directory structure
        if image_path.startswith('files/'):
            # Remove 'files/' prefix and create relative path
            rel_path = image_path[6:]  # Remove 'files/' prefix
        else:
            rel_path = image_path
        
        dst_file = dst_path / rel_path
        
        # Create parent directories
        dst_file.parent.mkdir(parents=True, exist_ok=True)
        
        if src_file.exists():
            try:
                if mode == "copy":
                    shutil.copy2(src_file, dst_file)
                elif mode == "symlink":
                    if dst_file.exists():
                        dst_file.unlink()
                    dst_file.symlink_to(src_file.absolute())
                else:
                    raise ValueError(f"Unknown mode: {mode}")
                
                collected.append(str(dst_file))
                if len(collected) % 100 == 0:
                    print(f"   ✅ Collected {len(collected)} images...")
                    
            except Exception as e:
                print(f"⚠️  Error processing {src_file}: {e}")
                missing.append(str(src_file))
        else:
            print(f"❌ Missing: {src_file}")
            missing.append(str(src_file))
    
    print(f"✅ Successfully collected {len(collected)} images")
    if missing:
        print(f"❌ Missing {len(missing)} images")
        with open(dst_path / "missing_images.txt", 'w') as f:
            for img in missing:
                f.write(f"{img}\n")
        print(f"📝 Missing images list saved to {dst_path / 'missing_images.txt'}")
    
    return collected


def create_index(collected_images: List[str], dst_root: str):
    """Create an index file of collected images."""
    index_file = Path(dst_root) / "collected_images_index.txt"
    
    with open(index_file, 'w') as f:
        f.write("# Collected Images Index\n")
        f.write(f"# Total images: {len(collected_images)}\n")
        f.write("# Generated by collect_referenced_images.py\n\n")
        
        for img in sorted(collected_images):
            f.write(f"{img}\n")
    
    print(f"📝 Index file created: {index_file}")


def create_zip(dst_root: str, zip_path: str):
    """Create a zip file of the collected images."""
    print(f"📦 Creating zip file: {zip_path}")
    
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(dst_root):
            for file in files:
                file_path = Path(root) / file
                arc_path = file_path.relative_to(Path(dst_root))
                zipf.write(file_path, arc_path)
    
    zip_size = Path(zip_path).stat().st_size / (1024 * 1024)  # MB
    print(f"✅ Zip file created: {zip_path} ({zip_size:.1f} MB)")


def main():
    parser = argparse.ArgumentParser(
        description="Collect referenced images from JSONL files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Copy images to subset folder
  python scripts/collect_referenced_images.py \\
    --jsonl src/data/processed/curriculum_train_final_clean.jsonl \\
    --src-root /path/to/full/dataset \\
    --dst-root subset_images \\
    --mode copy

  # Create symlinks (saves disk space)
  python scripts/collect_referenced_images.py \\
    --jsonl src/data/processed/curriculum_train_final_clean.jsonl \\
    src/data/processed/curriculum_val_final_clean.jsonl \\
    --src-root /path/to/full/dataset \\
    --dst-root subset_images \\
    --mode symlink \\
    --zip-out subset_images.zip
        """
    )
    
    parser.add_argument(
        '--jsonl', 
        nargs='+', 
        required=True,
        help='JSONL files to process'
    )
    parser.add_argument(
        '--src-root', 
        required=True,
        help='Source root directory containing the full dataset'
    )
    parser.add_argument(
        '--dst-root', 
        required=True,
        help='Destination root directory for subset'
    )
    parser.add_argument(
        '--mode', 
        choices=['copy', 'symlink'], 
        default='copy',
        help='Collection mode: copy files or create symlinks'
    )
    parser.add_argument(
        '--zip-out',
        help='Optional: create zip file of the subset'
    )
    
    args = parser.parse_args()
    
    print("🚀 Starting image collection process...")
    print(f"📁 Source root: {args.src_root}")
    print(f"📁 Destination root: {args.dst_root}")
    print(f"🔧 Mode: {args.mode}")
    
    # Extract image paths
    image_paths = extract_image_paths(args.jsonl)
    
    if not image_paths:
        print("❌ No image paths found in JSONL files")
        sys.exit(1)
    
    # Collect images
    collected = collect_images(image_paths, args.src_root, args.dst_root, args.mode)
    
    # Create index
    create_index(collected, args.dst_root)
    
    # Create zip if requested
    if args.zip_out:
        create_zip(args.dst_root, args.zip_out)
    
    print("🎉 Image collection completed!")
    print(f"📊 Total images collected: {len(collected)}")
    print(f"📁 Output directory: {args.dst_root}")
    if args.zip_out:
        print(f"📦 Zip file: {args.zip_out}")


if __name__ == "__main__":
    main()